include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules: # Dart 2.14.0-301.2.beta, lints 1.0.1
    - always_declare_return_types
    # - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    # - always_require_non_null_named_parameters lints/recommended
    # - always_specify_types
    # - always_use_package_imports
    # - annotate_overrides lints/recommended
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    # - avoid_empty_else lints/core
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    # - avoid_function_literals_in_foreach_calls lints/recommended
    - avoid_implementing_value_types
    # - avoid_init_to_null lints/recommended
    - avoid_js_rounded_ints
    # - avoid_multiple_declarations_per_line
    # - avoid_null_checks_in_equality_operators lints/recommended
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    # - avoid_relative_lib_imports lints/core
    # - avoid_renaming_method_parameters lints/recommended
    # - avoid_return_types_on_setters lints/recommended
    - avoid_returning_null
    - avoid_returning_null_for_future
    # - avoid_returning_null_for_void lints/recommended
    - avoid_returning_this
    - avoid_setters_without_getters
    # - avoid_shadowing_type_parameters lints/core
    # - avoid_single_cascade_in_expression_statements lints/recommended
    - avoid_slow_async_io
    - avoid_type_to_string
    # - avoid_types_as_parameter_names lints/core
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    # - await_only_futures lints/core
    # - camel_case_extensions lints/core
    # - camel_case_types lints/core
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    # - constant_identifier_names lints/recommended
    # - control_flow_in_finally lints/recommended
    # - curly_braces_in_flow_control_structures lints/core
    - depend_on_referenced_packages
    - deprecated_consistency
    - diagnostic_describe_all_properties
    - directives_ordering
    - do_not_use_environment
    # - empty_catches lints/core
    # - empty_constructor_bodies lints/recommended
    # - empty_statements lints/recommended
    - eol_at_end_of_file
    # - exhaustive_cases lints/recommended
    # - file_names lints/core
    - flutter_style_todos
    # - hash_and_equals lints/core
    # - implementation_imports lints/recommended
    - invariant_booleans
    # - iterable_contains_unrelated_type lints/core
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    # - library_names lints/recommended
    # - library_prefixes lints/recommended
    - library_private_types_in_public_api
    - lines_longer_than_80_chars
    # - list_remove_unrelated_type lints/core
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases
    # - no_duplicate_case_values lints/core
    - no_logic_in_create_state
    - no_runtimeType_toString
    # - non_constant_identifier_names lints/core
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    # - null_closures lints/recommended
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    # - overridden_fields lints/recommended
    - package_api_docs
    # - package_names lints/recommended
    # - package_prefixed_library_names lints/core
    - parameter_assignments
    # - prefer_adjacent_string_concatenation lints/recommended
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    # - prefer_collection_literals lints/recommended
    # - prefer_conditional_assignment lints/recommended
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    # - prefer_contains lints/recommended
    # - prefer_double_quotes
    # - prefer_equal_for_default_values lints/recommended
    # - prefer_expression_function_bodies
    # - prefer_final_fields lints/recommended
    - prefer_final_in_for_each
    - prefer_final_locals
    # - prefer_final_parameters
    # - prefer_for_elements_to_map_fromIterable lints/recommended
    - prefer_foreach
    # - prefer_function_declarations_over_variables lints/recommended
    # - prefer_generic_function_type_aliases lints/core
    - prefer_if_elements_to_conditional_expressions
    # - prefer_if_null_operators lints/recommended
    # - prefer_initializing_formals lints/recommended
    # - prefer_inlined_adds lints/recommended
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    # - prefer_is_empty lints/core
    # - prefer_is_not_empty lints/core
    # - prefer_is_not_operator lints/recommended
    # - prefer_iterable_whereType lints/core
    - prefer_mixin
    - prefer_null_aware_method_calls
    # - prefer_null_aware_operators lints/recommended
    - prefer_relative_imports
    - prefer_single_quotes
    # - prefer_spread_collections lints/recommended
    # - prefer_typing_uninitialized_variables lints/core
    # - prefer_void_to_null lints/recommended
    # - provide_deprecation_message lints/core
    # - public_member_api_docs
    # - recursive_getters lints/recommended
    - require_trailing_commas
    - sized_box_for_whitespace
    # - slash_for_doc_comments lints/recommended
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    # - type_init_formals lints/recommended
    - unawaited_futures
    - unnecessary_await_in_return
    # - unnecessary_brace_in_string_interps lints/recommended
    # - unnecessary_const lints/recommended
    # - unnecessary_final
    # - unnecessary_getters_setters lints/recommended
    - unnecessary_lambdas
    # - unnecessary_new lints/recommended
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    # - unnecessary_null_in_if_null_operators lints/recommended
    - unnecessary_nullable_for_final_variable_declarations
    # - unnecessary_overrides lints/core
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    # - unnecessary_string_escapes lints/recommended
    # - unnecessary_string_interpolations lints/recommended
    # - unnecessary_this lints/recommended
    # - unrelated_type_equality_checks lints/core
    - unsafe_html
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    # - use_function_type_syntax_for_parameters lints/recommended
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    # - use_rethrow_when_possible lints/recommended
    - use_setters_to_change_properties
    - use_string_buffers
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    # - valid_regexps lints/core
    # - void_checks lints/core
