name: dsalg
version: 0.2.0
description: >-
  A library with popular data structures and algorythms.
environment:
  sdk: ">=2.18.0 <3.0.0"
dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
  test: ^1.22.0
