name: dsalg
version: 0.1.0
description: >-
  A library with popular data structures and algorythms.
environment:
  # Update after stable release
  sdk: ">=2.15.0-82.1.beta <3.0.0"
dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.0
