name: dsalg
version: 0.3.0
description: >-
  A library with popular data structures and algorythms.
environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.24.0
