name: grids
version: 0.0.2
description: >-
  A library to render and work with polygonal fields.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  collection: ^1.15.0
dev_dependencies:
  build_runner: ^1.12.0
  build_web_compilers: ^2.16.0
  pedantic: ^1.11.0
  test: ^1.16.0
